swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: User accounts API
      description: API for fetching the user's accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User accounts are retrieved successully
          schema:
            $ref: "#/definitions/Accounts"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/accounts/{accountId}?month=transactionsMonth&year=transactionsYear:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Account Transaction API
      description: API to retrieve transactions from a current month’s account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          schema:
          type: integer
          required: true
          description: Numeric ID of the account to get
        - in: query
          name: month
          schema:
          type: integer
          description: The number of the month of the transactions to fetch
        - in: query
          name: year
          schema:
          type: integer
          description: The number of the year of the transactions to fetch
      produces:
        - application/json
      responses:
        "200":
          description: User transactions are retrieved successully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction API
      description: API to retrieve transactions from a current month’s account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: transactionId
          schema:
          type: integer
          required: true
          description: Numeric ID of the transaction to get

      produces:
        - application/json
      responses:
        "200":
          description: User transactions are retrieved successully
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
              body:
                $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction API
      description: API for updating the transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: transactionId
          schema:
          type: integer
          required: true
          description: Numeric ID of the transaction to update
        - in: body
          name: body
          description: Update the transaction
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
              notes:
                type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction retrieved successully
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
              body:
                $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Accounts:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          accounts:
            type: array
            items:
              $ref: "#/definitions/UserAccount"
  UserAccount:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      amount:
        type: number
      description:
        type: string
  Transactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transactions:
            type: array
            items:
              $ref: "#/definitions/Transaction"
  Transaction:
    type: object
    properties:
      id:
        type: integer
      accountID:
        type: integer
      createdAt:
        type: string
      description:
        type: string
      amount:
        type: number
      transaction-type:
        type: string
      category:
        type: string
      notes:
        type: string
